import { ArrowRight } from "lucide-react";
import { OperationalIcon, type OperationalIconKind } from "@/app/components/OperationalIcon";
import { SEO } from "@/app/components/SEO";
import { EditorialHero, EditorialSection, InlineLink } from "@/app/components/NarrativeComponents";
import { SingularityLearningCurve } from "@/app/components/SingularityLearningCurve";
import { createBreadcrumbSchema, createProductSchema } from "@/app/lib/structuredData";

const platformLearningCopy = "Because Last Mile sees the full lifecycle from first signal through verified recovery, AI can compare the decisions, handoffs, actions, delays, and return readings that shaped the result. No useful learning is lost, successful resolution steps do not have to be rediscovered, and approved improvements can be applied automatically the next time a similar issue appears.";

const memorySequence: ReadonlyArray<{ label: string; copy: string; kind: OperationalIconKind }> = [
  { label: "What changed", copy: "Source, time, quality, asset, and operating condition", kind: "signal" },
  { label: "What people decided", copy: "Context, recommendation, authority, and chosen response", kind: "decision" },
  { label: "What the operation did", copy: "Work, approvals, digital actions, handoffs, and delays", kind: "flow" },
  { label: "What happened next", copy: "Return readings, stability, recurrence, and measured result", kind: "verification" },
];

const authorityModes: ReadonlyArray<{ name: string; copy: string; kind: OperationalIconKind }> = [
  { name: "ASSIST", copy: "AI assembles context, finds similar history, and recommends a response. A person decides.", kind: "context" },
  { name: "AUTO", copy: "Infinit-Flow executes only the bounded digital steps already authorized by customer policy.", kind: "flow" },
  { name: "HUMAN AUTHORITY", copy: "People retain control of safety, isolation, physical work, and customer-governed changes.", kind: "people-authority" },
];

export function SSOMPage() {
  const description = "Singularity links readings, decisions, work, and results to the physical asset while preserving where each fact came from.";
  return <><SEO title="Singularity | Source-Linked Industrial Knowledge" description={description} canonicalPath="/singularity" jsonLd={[createProductSchema("Singularity", "/singularity", description), createBreadcrumbSchema([{ name: "Home", path: "/" }, { name: "Singularity", path: "/singularity" }])]} /><main className="lm-v2-page lm-product-story-page lm-product-story-page--singularity lm-singularity-story lm-singularity-v5">
    <EditorialHero eyebrow="SINGULARITY · SEMANTIC OPERATING MEMORY" title="One durable operating record for every physical asset." intro="Raw telemetry does not explain the operation. Singularity connects each reading to the asset, location, history, decision, action, and measured result that give it meaning." support="The record aligns with Unified Namespace architectures and uses the open Standardized Semantic Object Model to keep source identity, time, quality, relationships, and provenance intact." primary={{ label: "Review the Semantic Model", to: "/singularity#semantic-model" }} secondary={{ label: "Explore the Learning Continuum", to: "/singularity#learning-continuum" }} visual={<HeroImage />} />
    <OperatingMemoryThreat />
    <EditorialSection id="learning-continuum" eyebrow="THE OPERATIONAL LEARNING CONTINUUM" title="Move from reacting by hand to recognizing what comes next." intro="Every complete response adds usable history. As Last Mile follows an operation end to end, that record becomes a stronger foundation for earlier decisions, better response plans, and safely bounded automation." tone="grid" className="lm-singularity-continuum-section"><SingularityLearningCurve /><div className="lm-singularity-learning-payoff"><OperationalIcon kind="context" size="large" /><div><strong>Every response should make the next response smarter.</strong><p>{platformLearningCopy}</p></div></div></EditorialSection>
    <EarlierRecognition />
    <AuthorityBoundary />
  </main></>;
}

function HeroImage() {
  return <figure className="lm-enterprise-product-hero-image lm-enterprise-product-hero-image--semantic"><img src="/images/products/singularity/semantic-operating-record-v3.png" alt="Source-linked industrial records pass through semantic alignment and emerge as one durable equipment record." width="1672" height="941" fetchPriority="high" /></figure>;
}

function OperatingMemoryThreat() {
  return <EditorialSection id="semantic-model" eyebrow="THE THREAT OF OPERATIONAL AMNESIA" title="If the reason behind the fix disappears, the next shift starts over." intro="A maintenance note may capture the task, but not the weak signal that started the investigation, the options the team rejected, or the return readings that showed the machine was stable. Singularity keeps that full operating story together so the next team inherits more than a ticket summary."><div className="lm-singularity-memory-layout"><PersistentMemoryHero /><div className="lm-singularity-memory-spine">{memorySequence.map((item, index) => <article key={item.label}><OperationalIcon kind={item.kind} size="medium" /><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{item.label}</h3><p>{item.copy}</p></div>{index < memorySequence.length - 1 ? <ArrowRight aria-hidden="true" /> : null}</article>)}</div></div><div className="lm-singularity-foundation"><article><span>OPEN MEANING CONTRACT</span><h3>SSOM keeps the record portable.</h3><p>The Standardized Semantic Object Model defines portable operating meaning, identity, relationships, time, quality, evidence, provenance, conformance, and profiles.</p></article><article><span>GOVERNED LAST MILE RUNTIME</span><h3>Singularity keeps the memory useful.</h3><p>It preserves source identities, time-correct history, asset relationships, conditions, decisions, actions, and measured results without erasing where the information came from.</p></article></div></EditorialSection>;
}

function EarlierRecognition() {
  return <EditorialSection eyebrow="RECOGNIZE THE PATTERN BEFORE THE FAILURE" title="Use the history to give the next crew a head start." intro="When a familiar vibration pattern, sequence of alarms, or operating condition appears again, Singularity can bring forward the earlier response and the measurements that followed. The team starts with relevant history instead of reconstructing the problem from scratch."><div className="lm-enterprise-split-story"><figure className="lm-enterprise-story-image"><img src="/images/products/singularity/pattern-anticipation-v2.png" alt="A reliability engineer compares current compressor vibration with earlier patterns and the later stable result." width="1536" height="1024" loading="lazy" /></figure><div className="lm-enterprise-split-story__points"><article><span>01</span><div><h3>See the earlier pattern</h3><p>Connect the current change to the same asset, operating state, and history.</p></div></article><article><span>02</span><div><h3>Bring forward what mattered</h3><p>Show the decision, action, authority, and measured result from the earlier response.</p></div></article><article><span>03</span><div><h3>Act sooner with clear limits</h3><p>Recommend or automate only the steps allowed by current evidence and customer policy.</p></div></article></div></div></EditorialSection>;
}

function AuthorityBoundary() {
  return <EditorialSection eyebrow="AUTOMATION MUST EARN ITS TRUST" title="Learning can advance the response without taking authority away." intro="The goal is not automation for its own sake. The goal is to use retained operating knowledge to see problems earlier, choose a stronger response, and avoid preventable downtime while keeping clear authority over every consequential action." tone="grid" className="lm-singularity-governance-section"><div className="lm-singularity-authority">{authorityModes.map((mode) => <article key={mode.name}><OperationalIcon kind={mode.kind} size="medium" /><div><span>{mode.name}</span><p>{mode.copy}</p></div></article>)}</div><div className="lm-singularity-boundary"><div><OperationalIcon kind="security" size="large" /><span>THE NON-NEGOTIABLE BOUNDARY</span><h3>Current readings and customer authority remain in control.</h3><p>Models can identify patterns, assemble context, and recommend a response. They do not become operating truth simply because software produced them. Physical recovery still depends on current valid measurements.</p></div><div><span>DATA TRUST</span><h3>Learning persists. Customer facts stay protected.</h3><p>The architecture separates customer operations from cross-site learning. SSOM conformance does not grant contribution rights. Purpose, consent, minimization, transformation, provenance, retention, and model scope remain explicit, and aggregate learning cannot rewrite customer canonical facts.</p></div></div><nav className="lm-singularity-concept-links" aria-label="Related industrial concepts"><InlineLink to="/resources/industrial-concepts/industrial-ai">Read how governed industrial AI advances safely</InlineLink><InlineLink to="/resources/industrial-concepts/lights-out-operations">Understand the lights-out manufacturing horizon</InlineLink><InlineLink to="/resources/industrial-concepts/data-spaces">See how sovereign learning protects customer data</InlineLink></nav></EditorialSection>;
}

function PersistentMemoryHero() {
  return <figure className="lm-singularity-memory-hero" aria-labelledby="memory-hero-caption"><div className="lm-singularity-memory-hero__heading">SINGULARITY · PERSIST + LEARN</div><div className="lm-singularity-memory-hero__orbit" aria-hidden="true"><i /><i /><i /></div><ol><li><OperationalIcon kind="signal" size="medium" /><span>FIRST SIGNAL</span><strong>What changed?</strong></li><li><OperationalIcon kind="decision" size="medium" /><span>DECISION + ACTION</span><strong>What did we do?</strong></li><li><OperationalIcon kind="verification" size="medium" /><span>MEASURED RESULT</span><strong>What happened next?</strong></li></ol><div className="lm-singularity-memory-hero__core"><OperationalIcon kind="context" size="large" /><span>SINGULARITY</span><strong>One memory that keeps learning</strong><small>Asset · Condition · Decision · Action · Result</small></div><figcaption id="memory-hero-caption">The complete response becomes durable operating knowledge instead of leaving with the person, project, or source system.</figcaption></figure>;
}
