// Generated from canonical Industrial Concepts objects.
// Do not edit this file directly.

export const industrialConcepts = [
  {
    "contentId": "CONCEPT-UNS-001",
    "route": "/resources/industrial-concepts/uns-and-ssom",
    "slug": "uns-and-ssom",
    "cardTitle": "UNS and SSOM: moving industrial data is not the same as making it accountable",
    "cardCopy": "The customer UNS distributes current information. SSOM preserves identity, meaning, evidence, and lifecycle continuity.",
    "articleTitle": "UNS and SSOM: moving industrial data is not the same as making it accountable",
    "canonicalPosition": "A Unified Namespace and SSOM are complementary. The UNS is the customer's real-time communication and discovery fabric. SSOM is the vendor-neutral semantic and evidence contract. Infinit-Signal bridges them by preserving UNS runtime context while producing governed SSOM-conformant records for Singularity.",
    "paragraphs": [
      "A Unified Namespace can solve an important industrial problem: it gives publishers and consumers a shared, event-driven place to make current operational information available. In many implementations, MQTT supplies publish/subscribe transport and Sparkplug adds an industrial topic namespace, payload representation, and session-state model. This can reduce point-to-point integration and make plant information easier to discover.",
      "But availability is not the same as operational truth.",
      "A topic path tells a consumer where information was published. It does not, by itself, establish that two source identifiers refer to the same physical asset, that a retained message is current, that a value arrived in event-time order, that a replay should influence a live decision, or that a cleared alarm proves the underlying impairment is gone. Those questions require identity, time, quality, provenance, evidence, policy, and lifecycle continuity.",
      "That is the division of responsibility between a customer UNS and Last Mile. Infinit-Signal subscribes to configured sources and preserves publisher, topic, QoS, retain flag, timestamp, session, Sparkplug birth/death, sequence, alias, and source-quality context. It classifies freshness, duplicates, retained messages, replay, and unresolved mappings before a record can influence the operating model. The original topic remains visible as a source address; it does not silently become canonical asset identity.",
      "Singularity then applies the SSOM contract. It gives assets stable identities and scoped external aliases, represents many-to-many and time-varying relationships, preserves accepted history and evidence, and connects Conditions, decisions, actions, return measurements, and verified Outcomes. Current state can still be distributed through the UNS, but the evidence chain remains durable outside the broker's session and retention behavior.",
      "The result is not a choice between UNS and SSOM. The UNS makes industrial information available. SSOM makes that information portable, interpretable, governable, and accountable across systems and time."
    ],
    "operatingResponse": [
      "Cooling-pump state arrives on `dc03/chw/loop-b/chwp-02/state`. The customer UNS transports that publication and retains its broker, topic, QoS, session, and publisher responsibilities. Infinit-Signal preserves that context, rejects a duplicate event and a pressure sample stale by 47 seconds, and maps the accepted source identities to canonical asset `CHWP-02`. Singularity then carries one accountable Cooling Loop B Condition through work and telemetry-established recovery; the topic never becomes the asset identity or the recovery decision by itself."
    ],
    "comparison": [
      [
        "Customer UNS",
        "Infinit-Signal",
        "Singularity / SSOM"
      ],
      [
        "Topics, transport, session, distribution",
        "Subscription, preservation, qualification, mapping, COR creation",
        "Canonical identity, topology, Conditions, history, evidence, Outcomes"
      ],
      [
        "Current-state availability",
        "Live/replay/stale/duplicate classification",
        "Durable time-correct operational memory"
      ],
      [
        "Source/runtime identifiers",
        "Source-to-canonical crosswalk",
        "Canonical identity and lifecycle continuity"
      ],
      [
        "MQTT/Sparkplug compatibility",
        "Separate compatibility and mapping evidence",
        "SSOM conformance and semantic governance"
      ]
    ],
    "sources": [
      {
        "label": "Eclipse Sparkplug Specification - MQTT topic namespace, payload, and session state",
        "url": "https://sparkplug.eclipse.org/specification/"
      }
    ],
    "boundary": "Last Mile owns the UNS; MQTT equals UNS; a topic is canonical identity; broker publication equals accepted truth; Sparkplug conformance equals SSOM conformance."
  },
  {
    "contentId": "CONCEPT-SEMANTIC-001",
    "route": "/resources/industrial-concepts/semantic-interoperability",
    "slug": "semantic-interoperability",
    "cardTitle": "Connected is not yet interoperable",
    "cardCopy": "Why protocols move values but semantic interoperability preserves operational meaning.",
    "articleTitle": "Connected is not yet interoperable",
    "canonicalPosition": "Protocol connectivity moves values. Semantic interoperability preserves what those values refer to, how they relate, what quality and time mean, and how they remain interpretable when systems, vendors, and sites disagree.",
    "paragraphs": [
      "Industrial integration often celebrates the moment a value can move from one system to another. That is necessary, but it is not the hard part. A pressure value without a stable asset identity, engineering meaning, time basis, quality, source authority, and relationship to the operating process is connected data—not dependable operational context.",
      "Semantic interoperability means two systems can exchange information and preserve meaning well enough to use it correctly. In physical operations, that includes asset class and instance identity; units and quantity kind; topology and dependency; event and observation semantics; source and event time; quality and uncertainty; and the evidence required to explain a decision later.",
      "Last Mile does not attempt to erase strong source semantics. OPC UA information models, Companion Specifications, Sparkplug metrics, historian points, ISA-95 structures, equipment models, and customer naming conventions may all contain valuable meaning. Infinit-Signal preserves those source representations and maps them through governed profiles. Singularity/SSOM gives the resulting facts a portable operational contract and retains the crosswalk back to the source.",
      "This matters most when one physical asset has five names, when a functional relationship differs from a physical hierarchy, when equipment is replaced, when a source changes vendors, or when an AI system needs to understand whether two observations are comparable. The goal is not to force every source into one flattened taxonomy. It is to establish canonical continuity while keeping the original evidence and uncertainty visible.",
      "Semantic interoperability is therefore the foundation for cross-vendor orchestration. Without it, automation scales interfaces. With it, operations can scale accountable meaning."
    ],
    "operatingResponse": [
      "The same chilled-water pump appears as Rockwell tag `B3_CHW_P02_CMD`, BMS status `B3_CHW_P02_STS`, Ignition path `[DC03]CHW/LoopB/CHWP-02`, HighByte instance `dc03.loop_b.chwp_02`, MQTT topic `dc03/chw/loop-b/chwp-02/state`, historian point `DC03_CHWP02_AMPS`, and SAP equipment `CHWP-02`. Semantic interoperability preserves each source identity and validity period while resolving the shared asset and its topology: CHWP-02 → Cooling Loop B → Hall 3 → N+1 secondary pumping path."
    ],
    "comparison": [],
    "sources": [
      {
        "label": "OPC UA information modeling and enterprise interoperability",
        "url": "https://opcfoundation.org/about/opc-technologies/opc-ua/"
      },
      {
        "label": "OPC UA Companion Specifications and domain models",
        "url": "https://opcfoundation.org/about/opc-technologies/opc-ua/ua-companion-specifications/"
      }
    ],
    "boundary": "Do not imply that connectivity alone establishes interoperability, that source semantics should be erased, or that every source can be flattened into one taxonomy without preserving evidence and uncertainty."
  },
  {
    "contentId": "CONCEPT-OPCUA-001",
    "route": "/resources/industrial-concepts/opc-ua",
    "slug": "opc-ua",
    "cardTitle": "OPC UA and Companion Specifications",
    "cardCopy": "Preserve strong source models and connect them to the cross-system operating outcome.",
    "articleTitle": "Preserve the source model, then connect it to the operating outcome",
    "canonicalPosition": "OPC UA is a secure, platform-independent industrial interoperability architecture with information modeling and multiple communication patterns. Companion Specifications add domain- and equipment-specific models. Infinit-Signal should preserve and map that source meaning; SSOM should not pretend it never existed.",
    "paragraphs": [
      "OPC UA is more than a protocol for reading tags. Its architecture includes discovery, security, subscriptions, events, methods, history, and an extensible information model. Companion Specifications build industry and equipment models on that foundation so participants can exchange more than anonymous values.",
      "That makes OPC UA an important source of meaning for Last Mile. An Infinit-Signal OPC UA profile should preserve endpoint and application identity, namespace URI, NodeId, browse path, server and source timestamps, status code, engineering units, event types, and the applicable Companion Specification model. Mapping must remain versioned and reversible so the original representation is always available for evidence and diagnosis.",
      "SSOM adds a different scope. It connects source-specific objects to canonical operational identity across OPC UA, MQTT/UNS, historians, work systems, and service providers. It preserves relationships and evidence over time and connects the operating condition to decisions, work, return measurements, and outcomes.",
      "The correct architecture is therefore additive: keep OPC UA's source information model; map it through governed profiles; use Singularity/SSOM for cross-system operational continuity. Last Mile should never market SSOM as a reason to discard a customer's Companion Specification investment."
    ],
    "operatingResponse": [
      "An OPC UA server may expose the `CHWP-02` motor-current observation with namespace URI, NodeId, browse path, server and source timestamps, status code, engineering unit `A`, and equipment-model context. Infinit-Signal preserves those fields and maps the observation to the canonical pump without flattening away its source model. The resulting 0.6 A value can contribute to the qualified Cooling Loop B Condition only when its identity, time, and quality satisfy the configured contract."
    ],
    "comparison": [],
    "sources": [
      {
        "label": "OPC UA architecture",
        "url": "https://opcfoundation.org/about/opc-technologies/opc-ua/"
      },
      {
        "label": "OPC UA Companion Specifications",
        "url": "https://opcfoundation.org/about/opc-technologies/opc-ua/ua-companion-specifications/"
      }
    ],
    "boundary": "Every OPC UA server uses a Companion Specification; Last Mile is OPC-certified; a representative endpoint is a validated connector; SSOM replaces OPC UA models."
  },
  {
    "contentId": "CONCEPT-TWIN-001",
    "route": "/resources/industrial-concepts/digital-twins",
    "slug": "digital-twins",
    "cardTitle": "Digital twins, AAS, and operational memory",
    "cardCopy": "Asset representation and accountable response history solve different, complementary problems.",
    "articleTitle": "A digital representation is valuable. Operational accountability requires a history of what happened next.",
    "canonicalPosition": "Digital twin is a broad term. The Asset Administration Shell provides an interoperable Industry 4.0 implementation pattern for representing asset information across a lifecycle. Singularity is not positioned as a replacement for every digital twin; it supplies cross-system operational identity, evidence, Conditions, response, and outcome memory.",
    "paragraphs": [
      "Industrial digital twins can describe the characteristics, state, parameters, capabilities, and lifecycle information of an asset. The Asset Administration Shell makes that idea more concrete by defining an interoperable representation composed of submodels and usable across manufacturers and applications.",
      "Last Mile should embrace that work, not compete with the term. An AAS, engineering twin, performance twin, simulation model, or vendor equipment model can remain authoritative for its intended domain. Infinit-Signal can preserve its identifiers and model context; Singularity can link the representation to the canonical operational asset and to other source identities.",
      "The Last Mile contribution begins where representation must become accountable operating memory. Which Condition affected the asset? What evidence qualified it? Who held authority? What work was requested and completed? Which return measurements proved recovery? Did the impairment recur? Those questions cross data, work, provider, and operational systems that no single equipment twin necessarily owns.",
      "That distinction keeps the architecture honest. AAS and other digital-twin models can provide rich asset semantics. Singularity/SSOM provides the time-correct cross-system thread from evidence to verified outcome. Together they are stronger than a claim that one model replaces all others."
    ],
    "operatingResponse": [
      "An equipment twin or AAS can remain authoritative for the technical representation of chilled-water pump `CHWP-02`. Singularity links that representation to the BMS, MQTT, historian, SAP, and provider identities and preserves what happened next: the reduced-redundancy Condition, owner, work order, field completion, return measurements, 15-minute stability window, and recurrence state. The representation and the operational outcome memory remain complementary."
    ],
    "comparison": [],
    "sources": [
      {
        "label": "Industrial Digital Twin Association technology and AAS overview",
        "url": "https://industrialdigitaltwin.org/en/technology"
      }
    ],
    "boundary": "Singularity is a universal digital twin; Last Mile implements the AAS standard unless evidence exists; all twin data may be shared; visual simulation equals operational truth."
  },
  {
    "contentId": "CONCEPT-THREAD-001",
    "route": "/resources/industrial-concepts/operational-outcome-thread",
    "slug": "operational-outcome-thread",
    "cardTitle": "The digital thread should not stop at the work order",
    "cardCopy": "Last Mile's operational outcome thread connects evidence, response, return measurements, and recurrence.",
    "articleTitle": "The digital thread should not stop at the work order",
    "canonicalPosition": "The digital thread commonly connects information across design, manufacturing, quality, and product support. Last Mile contributes a focused operational outcome thread: condition, evidence, decision, authority, work, return measurement, verified result, and recurrence.",
    "paragraphs": [
      "Manufacturers have spent years connecting product and process information across engineering, production, inspection, and support. NIST describes the digital thread as trusted lifecycle information that can move through those activities and support feedback instead of remaining trapped in one-way silos.",
      "Physical operations need a complementary thread. When a pump fails to start, a refrigeration circuit loses capacity, or compressed-air demand becomes abnormal, the critical information is not only the design definition or maintenance record. Operations need a time-correct chain that explains what evidence was observed, how the impairment was qualified, who owned the response, what action occurred, whether the physical state recovered, and whether it remained recovered.",
      "Last Mile calls this the operational outcome thread. Infinit-Signal preserves and qualifies source evidence. Singularity attaches that evidence to canonical identity and the accountable Condition. Infinit-Flow coordinates work and authority. Infinit-Control keeps the case visible. Singularity then evaluates return measurements and preserves the Outcome.",
      "The thread does not replace PLM, MES, QMS, CMMS, historian, or digital-twin systems. It gives them a shared operational result. A work order can be linked to the outcome without being allowed to define it. That closes a gap that ordinary lifecycle integration often leaves open."
    ],
    "operatingResponse": [
      "For Cooling Loop B, SAP work `WO-18427` closes at 15:02:41. The operational outcome thread keeps the Condition open through the return-measurement window: pump status, motor current, differential pressure, rack inlet temperature, and pressure stability must remain valid and in criteria until 15:17:41. Recovery is established at 15:17:42. The work record is linked to the result but cannot define it."
    ],
    "comparison": [],
    "sources": [
      {
        "label": "NIST Digital Thread for Smart Manufacturing",
        "url": "https://www.nist.gov/programs-projects/digital-thread-smart-manufacturing"
      }
    ],
    "boundary": "Do not imply that the operational outcome thread replaces PLM, MES, QMS, CMMS, historian, digital-thread, or digital-twin systems. Work status may be linked to an Outcome but cannot define it."
  },
  {
    "contentId": "CONCEPT-INDUSTRIAL-AI-001",
    "route": "/resources/industrial-concepts/industrial-ai",
    "slug": "industrial-ai",
    "cardTitle": "Industrial AI must know what it is allowed to do—and whether it worked",
    "cardCopy": "Governed context, authority, exception handling, and verified outcomes are prerequisites for responsible agents.",
    "articleTitle": "Industrial AI must know what it is allowed to do—and whether it worked",
    "canonicalPosition": "Industrial AI requires governed context, explicit authority, current valid evidence, and verified outcomes. Last Mile supports a progression from deterministic automation to assisted and bounded agent action without treating model output as operational truth.",
    "paragraphs": [
      "An industrial model can identify a pattern, summarize evidence, recommend a response, or plan a sequence. None of those outputs should become an operating fact simply because a model produced it. Physical operations add constraints that ordinary enterprise automation can avoid: stale sensors, uncertain identities, safety boundaries, degraded redundancy, physical work, and outcomes that must be measured after the action.",
      "Last Mile's architecture gives industrial AI a governed substrate. Singularity provides canonical assets, topology, Conditions, evidence, quality, history, and prior Outcomes. Infinit-Flow supplies policy, approvals, timers, permitted actions, receipts, and stop conditions. Infinit-Control makes the evidence, recommendation, authority, and result legible to the operator.",
      "This produces three clear modes. AUTO executes a bounded digital step already authorized by policy. ASSIST assembles evidence or proposes a response while an operator decides. HUMAN AUTHORITY retains control over physical work, safety, LOTO, and customer-governed changes. A model or agent must declare which mode applies.",
      "The most important learning signal comes after the action. Did pressure return to band? Did drawdown recover across three cycles? Did the same impairment recur? Outcome evidence makes improvement possible without rewarding an agent for merely completing a task.",
      "CESMII describes smart manufacturing as proactive and semi-autonomous, with automated decisions for routine situations and people involved in non-routine ones. Last Mile's position is aligned but precise: autonomy should increase only as identity, evidence, policy, exception handling, and outcome verification become stronger."
    ],
    "operatingResponse": [
      "At `LS-07`, current-rate arithmetic shows approximately 06:40 to the 9.0 ft high-high level if the observed +0.18 ft/min rise continues. That is a disclosed linear estimate, not a predictive model. An ASSIST function can assemble the wet-well, pump, flow, standby, and owner context; customer policy retains physical and control authority. The result is learned only after three complete drawdown cycles satisfy the configured recovery contract."
    ],
    "comparison": [],
    "sources": [
      {
        "label": "CESMII First Principles of Smart Manufacturing",
        "url": "https://www.cesmii.org/first-principles-of-smart-manufacturing/"
      }
    ],
    "boundary": "AI replaces operators; a model can authorize itself; generated text is evidence; task completion equals outcome; all Last Mile functions are currently implemented AI."
  },
  {
    "contentId": "CONCEPT-I50-001",
    "route": "/resources/industrial-concepts/industry-5-0",
    "slug": "industry-5-0",
    "cardTitle": "Industry 5.0 and human authority",
    "cardCopy": "Human-centricity, sustainability, and resilience require more than faster automation.",
    "articleTitle": "More automation is not the same as more industrial intelligence",
    "canonicalPosition": "Industry 5.0 is a human-centric, sustainable, and resilient industrial vision—not a new automation version number. Last Mile supports it by keeping authority explicit, making degraded states and resilience visible, and verifying resource and operating outcomes.",
    "paragraphs": [
      "Industry 4.0 helped focus industry on connectivity, cyber-physical systems, data, and automation. The European Commission's Industry 5.0 framing broadens the objective around three priorities: human-centricity, sustainability, and resilience.",
      "That framing matters for Last Mile because operational intelligence is not simply the fastest automated response. A system must show who owns the condition, what authority is retained, what evidence supports the recommendation, how the response affects operating resilience, and whether the intended physical result occurred.",
      "Last Mile's AUTO, ASSIST, and HUMAN AUTHORITY modes make that boundary visible. Routine digital correlation, notification, and case creation can occur automatically. Evidence and recommended action can be assembled for an operator. Physical work, safety decisions, and control changes remain under customer authority where policy requires it.",
      "Resilience also needs a better measure than ticket volume. Reduced redundancy, unavailable standby capacity, failed recovery, insufficient return data, and recurrence should remain visible even when the alarm console looks quiet. Sustainability requires the same discipline: compressed-air flow or aeration energy should be measured against operating context and verified after intervention, not converted into a generic claim.",
      "The Last Mile position is therefore practical Industry 5.0: use technology to strengthen people, resilience, and resource outcomes while retaining accountability for the physical world."
    ],
    "operatingResponse": [
      "At wastewater station `LS-07`, AUTO time-aligns level, rate, current, speed, flow, and standby evidence. ASSIST presents a degraded-capacity Condition and the approved response to Luis Ortega. Collection Systems retains isolation, LOTO, standby-pump, and field-work authority. Recovery requires three complete drawdown cycles with valid flow, current, and level evidence; faster automation does not replace human accountability or resilience criteria."
    ],
    "comparison": [],
    "sources": [
      {
        "label": "European Commission Industry 5.0",
        "url": "https://research-and-innovation.ec.europa.eu/research-area/industrial-research-and-innovation/industry-50_en"
      }
    ],
    "boundary": "Do not use Industry 5.0 as a synonym for more automation, claim compliance, or imply that customer safety and physical-work authority have transferred to Last Mile."
  },
  {
    "contentId": "CONCEPT-OTSEC-001",
    "route": "/resources/industrial-concepts/ot-security",
    "slug": "ot-security",
    "cardTitle": "OT security and explicit trust boundaries",
    "cardCopy": "Connectivity must preserve physical performance, reliability, safety, least privilege, and safe degradation.",
    "articleTitle": "Connected operations need explicit trust boundaries",
    "canonicalPosition": "Industrial connectivity must preserve the performance, reliability, and safety requirements of OT. Last Mile applies least privilege, identity, segmentation-aware deployment, policy, audit, and bounded action without assuming enterprise IT controls can be copied into plant operations unchanged.",
    "paragraphs": [
      "Operational technology interacts with the physical environment. Security decisions therefore affect not only confidentiality but also process availability, safety, environmental protection, and the ability to recover. NIST's OT security guidance emphasizes these unique performance, reliability, and safety requirements.",
      "Last Mile should connect through customer-approved zones and conduits, not flatten them. Infinit-Signal supports boundary-local software, outbound-oriented secure delivery where appropriate, source-specific identities, certificate and secret rotation, least-privilege subscriptions, and evidence of connection and mapping changes. A customer UNS or OPC UA environment retains its own authentication, authorization, network, and session responsibilities.",
      "Within the platform, tenant isolation, workload identity, encryption, audit, and policy govern access to canonical facts and product-private state. Infinit-Flow commands are separately authorized, idempotent, time-bounded, and reconciled with receipts. HUMAN AUTHORITY remains explicit for physical work and control changes.",
      "Zero trust in this context does not mean constant cloud reachability or aggressive controls that disrupt operations. It means no connection, user, service, device identity, or agent receives implicit authority merely because it is inside a network. Access is scoped, verified, monitored, and revocable, with safe degraded behavior."
    ],
    "operatingResponse": [
      "At lift station `LS-07`, Infinit-Signal receives customer-approved wet-well, pump, current, speed, and flow evidence through an explicitly authorized boundary. The connection receives only the subscriptions and credentials required for that evidence. Infinit-Flow may create a digital case automatically, but pump isolation, LOTO, and physical repair remain under Collection Systems HUMAN AUTHORITY. Loss of the cloud path cannot become authority for safety control or hide the degraded station state."
    ],
    "comparison": [],
    "sources": [
      {
        "label": "NIST SP 800-82 Rev. 3, Guide to Operational Technology Security",
        "url": "https://csrc.nist.gov/pubs/sp/800/82/r3/final"
      }
    ],
    "boundary": "Last Mile certifies customer compliance; cloud access is required for safety control; IT zero-trust patterns may ignore OT availability; any agent can write to control systems."
  },
  {
    "contentId": "CONCEPT-DATASPACE-001",
    "route": "/resources/industrial-concepts/data-spaces",
    "slug": "data-spaces",
    "cardTitle": "Industrial data spaces and sovereign learning",
    "cardCopy": "Cross-company insight without surrendering participant control or making consent implicit.",
    "articleTitle": "Learning across industry without surrendering control",
    "canonicalPosition": "Industrial data spaces address governed sharing across organizations while preserving participant control, identity, usage policy, and responsibility. They are relevant to Singularity's future Data Trust model, but Last Mile must not claim a data-space implementation until the required protocols and governance are implemented.",
    "paragraphs": [
      "Industrial organizations increasingly need information that crosses company boundaries: supplier quality, asset service, emissions, product lifecycle, regulatory evidence, and collaborative AI. The same information may reveal operating practices, production capacity, customer relationships, or intellectual property. Useful sharing therefore requires more than a central repository and a legal disclaimer.",
      "Data spaces are designed around governed, federated exchange. Participants retain control over what they make available, to whom, for what purpose, under which usage conditions, and with what identity and trust mechanisms. The International Data Spaces Association describes manufacturing data spaces as federated rather than centralized, interoperable rather than uniform, and governed rather than ad hoc.",
      "That model is directionally aligned with Singularity's Data Trust. SSOM can give contributed operational facts portable identity, provenance, quality, and lifecycle meaning. Singularity can apply tenant, purpose, consent, minimization, transformation, retention, and model-use policy before any cross-site or cross-company learning occurs.",
      "The boundary is essential. SSOM conformance does not grant contribution consent. A customer operational record is not available to a shared model merely because it is technically compatible. Customer operations must continue even when contribution is disabled, revoked, or delayed.",
      "Last Mile should first implement auditable consent and purpose controls inside the platform. Dataspace Protocol or connector compatibility can be evaluated later as a separate maturity claim."
    ],
    "operatingResponse": [
      "A cold-storage operator may choose to contribute transformed refrigeration-outcome patterns for a defined service or learning purpose while withholding product, inventory, or site-identifying evidence. The Freezer 2 operational record and its current response continue inside the customer boundary whether contribution is enabled, delayed, or revoked. SSOM compatibility makes the meaning portable; explicit consent and purpose policy determine whether anything is shared."
    ],
    "comparison": [],
    "sources": [
      {
        "label": "International Data Spaces Association manufacturing data spaces",
        "url": "https://internationaldataspaces.org/manufacturing-data-spaces-whats-actually-taking-shape/"
      }
    ],
    "boundary": "Do not imply that Last Mile currently implements a data-space protocol, that technically compatible records are available for shared learning, or that SSOM conformance grants contribution consent."
  },
  {
    "contentId": "CONCEPT-COMPOSABLE-001",
    "route": "/resources/industrial-concepts/composable-manufacturing",
    "slug": "composable-manufacturing",
    "cardTitle": "Composable manufacturing beyond the connector",
    "cardCopy": "Discoverable capabilities still require semantics, commissioning, policy, and outcome verification.",
    "articleTitle": "Composable operations need more than a new connector",
    "canonicalPosition": "Modular industrial operations depend on discoverable capabilities, interoperable models, safe commissioning, and governed orchestration. Last Mile can help preserve identity and coordinate operating response, but it does not replace controls engineering or claim instantaneous plug-and-produce.",
    "paragraphs": [
      "The promise of plug-and-produce is attractive: add or replace an industrial module and allow the surrounding system to discover its identity, capabilities, data, and services with less custom integration. In practice, physical compatibility, safety, controls, network trust, semantics, commissioning, and operating procedures still matter.",
      "OPC UA information models, Companion Specifications, AAS submodels, and other capability descriptions can make equipment more discoverable and portable. Singularity/SSOM can preserve canonical identity when a device is replaced, connect source models to plant topology, and record which capabilities and relationships are valid over time. Infinit-Flow can bind workflows only to assets whose type, capability, site, role, quality, and freshness satisfy the workflow contract.",
      "That creates a useful operational layer around modularity. A new module can enter the operating model through governed mapping and conformance; procedures and response logic can reference compatible capabilities; and post-change outcomes can be verified from telemetry.",
      "The honest boundary remains important. Last Mile does not certify mechanical compatibility, generate PLC logic, approve safety functions, or eliminate commissioning. It makes the operational context and accountability around composable equipment more durable."
    ],
    "operatingResponse": [
      "If a replacement pump module is commissioned into Cooling Loop B, its OPC UA model or AAS submodel can describe capabilities and source identifiers. Singularity can preserve succession from the prior equipment identity, while Infinit-Flow binds the existing response only after the replacement asset satisfies the required type, site, capability, quality, and freshness contract. Commissioning, PLC logic, mechanical compatibility, and safety approval remain controls-engineering and customer responsibilities."
    ],
    "comparison": [],
    "sources": [
      {
        "label": "OPC UA Companion Specifications",
        "url": "https://opcfoundation.org/about/opc-technologies/opc-ua/ua-companion-specifications/"
      },
      {
        "label": "Industrial Digital Twin Association",
        "url": "https://industrialdigitaltwin.org/en/technology"
      }
    ],
    "boundary": "Do not imply instantaneous plug-and-produce, mechanical compatibility, automatic safety approval, generated PLC logic, eliminated commissioning, or implemented Last Mile composable-manufacturing capability."
  },
  {
    "contentId": "CONCEPT-LIGHTSOUT-001",
    "route": "/resources/industrial-concepts/lights-out-operations",
    "slug": "lights-out-operations",
    "cardTitle": "The dark factory is not a responsibility-free factory",
    "cardCopy": "Less routine human presence increases the need for trustworthy evidence and accountable recovery.",
    "articleTitle": "The dark factory is not a responsibility-free factory",
    "canonicalPosition": "“Dark factory” is a provocative label, not a Last Mile product claim. Use **lights-out manufacturing** or **autonomous operations** to discuss an operating model with less routine human presence and stronger requirements for evidence, policy, exception handling, and verified recovery.",
    "paragraphs": [
      "Lights-out manufacturing imagines production continuing with little or no routine human presence. Robotics, machine vision, automated material movement, predictive systems, and software agents can reduce manual intervention in repeatable work. But removing a person from the line does not remove the need to know what happened, who or what had authority, and whether the physical result was achieved.",
      "Autonomous operations magnify the cost of weak context. A stale retained message can look current. One asset may have different identities across controls and maintenance. A task can complete without restoring capacity. A system can repeatedly clear and recreate the same alarm without learning that the impairment recurred.",
      "Last Mile's relevance is the accountability layer around that autonomy. Infinit-Signal qualifies evidence. Singularity maintains canonical identity, Conditions, and history. Infinit-Flow executes only bounded policy-authorized steps and routes exceptions to human authority. Infinit-Control makes the degraded state and response visible. Return telemetry determines the Outcome.",
      "This is not a claim that Last Mile can operate a factory without people. It is a design position: as routine human involvement decreases, evidence, semantic continuity, authority, safe failure, and outcome verification must become more rigorous—not less."
    ],
    "operatingResponse": [
      "An unattended off-shift compressed-air system can automatically detect 1,860 SCFM demand and 355 kW power while Zone 4 header pressure is only 88.6 psig. AUTO may qualify the evidence and create the case; ASSIST may assemble the affected-zone inspection; HUMAN AUTHORITY retains isolation and repair. The response succeeds only when the configured pressure, flow, power, specific-power, and 30-minute stability criteria pass—not when an agent or work task reports completion."
    ],
    "comparison": [],
    "sources": [
      {
        "label": "CESMII First Principles of Smart Manufacturing",
        "url": "https://www.cesmii.org/first-principles-of-smart-manufacturing/"
      },
      {
        "label": "European Commission Industry 5.0",
        "url": "https://research-and-innovation.ec.europa.eu/research-area/industrial-research-and-innovation/industry-50_en"
      }
    ],
    "boundary": "Do not imply that Last Mile currently operates factories autonomously or that less routine human presence removes responsibility, safety authority, exception handling, or recovery requirements."
  }
] as const;
